#!/bin/sh

echo "Running GCAM"

OUTPUT="/home/peeyush/Desktop/gcam_test_data/test_26_OCT_17/"
INPUT="/home/peeyush/Desktop/gcam_test_data/test_26_OCT_17/input_gene_list.csv"
DATABASE="/home/peeyush/Desktop/gcam_test_data/resources"

if [ -z "$1" ]; then
    echo "No additional arguments for run...."
    python gcamrun genebased "-o" "$OUTPUT" "-p" "$INPUT" "-d" "$DATABASE"
elif [ -z "$2" ]; then
    echo "There is one arguments: $1"
    python gcamrun genebased "-o" "$OUTPUT" "-p" "$INPUT" "-d" "$DATABASE" "$1"
else
    echo "There are two arguments: $1 $2"
    python gcamrun genebased "-o" "$OUTPUT" "-p" "$INPUT" "-d" "$DATABASE" "$1" "$2"
fi
